# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  👋 Thanks for opening your first issue here! If you have a question about using Electron Packager, read the [support docs](https://github.com/electron/packager/blob/main/SUPPORT.md). If you're reporting a 🐞 bug, please make sure you include steps to reproduce it. Development and issue triage is community-driven, so please be patient and we will get back to you as soon as we can.

  To help make it easier for us to investigate your issue, please follow the [contributing guidelines](https://github.com/electron/packager/blob/main/CONTRIBUTING.md#before-opening-bug-reportstechnical-issues).

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Thanks for opening a pull request!

  Here are some highlighted action items that will help get it across the finish line, from the
  [pull request guidelines](https://github.com/electron/packager/blob/main/CONTRIBUTING.md#filing-pull-requests):
  - Follow the [JavaScript coding style](https://standardjs.com/).
  - Run `npm run lint` locally to catch formatting errors earlier.
  - Document any user-facing changes in `NEWS.md` and other docs.
  - Include tests when adding/changing behavior.

  Development and triage is community-driven, so please be patient and we will get back to you as soon as we can.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Thanks for your contribution! 🎉

# Configuration for request-info - https://github.com/behaviorbot/request-info

# *Required* Comment to reply with
requestInfoReplyComment: >
  Thanks for filing this issue/PR! It would be much appreciated if you could provide us with more information so we can effectively analyze the situation in context.

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs info

checkIssueTemplate: true
checkPullRequestTemplate: true
