blank_issues_enabled: false

contact_links:
  - name: Question
    url: https://discord.gg/APGC3k5yaH
    about: "Please ask questions about using Electron Packager in the official Electron Discord server, at the #electron-packager channel."
