name: Test

on:
  pull_request:
  schedule:
    - cron: '0 22 * * 3'
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    name: Test
    strategy:
      matrix:
        node-version:
          - '22.22.x'
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'yarn'
      - name: Setup CI Environment
        run: test/ci/before_install.sh
      - name: Install
        run: yarn install --immutable
      - name: Build
        run: yarn build
      - name: Electron Cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/electron
          key: v1-electron-cache-${{ matrix.os }}
      - name: Download Electron binaries
        run: node test/ci/download-electron.ts
      - name: Lint
        run: yarn run lint
      - name: Test
        run: |
          yarn run test
      - name: Build Docs
        run: yarn run build:docs
